config/routes.rb
Rails.application.routes.draw do
  root :to => "brands#index"

  resources :brands
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
    @brands = Brand.all
  end

  def new
    @brand = Brand.new
  end

  # SINGLE IMAGE
  # def create
  #   brand = Brand.new brand_params

  #   if params[:brand][:image].present?
  #     req = Cloudinary::Uploader.upload params[:brand][:image]
  #     brand.image = req["public_id"]
  #   end
  #   brand.save
  #   redirect_to brand_path(brand)
  # end

  # MULTIPLE IMAGES
  def create
    brand = Brand.new brand_params

    if params[:brand][:images].present?
      params[:brand][:images].each do |image|
        req = Cloudinary::Uploader.upload image
        brand.images << req["public_id"]
      end
    end

    brand.save
    redirect_to brand_path
  end

  def edit
    @brand = Brand.find params[:id]
  end

  def update
    brand = Brand.find params[:id]

    if params[:brand][:image].present?
      req = Cloudinary::Uploader.upload params[:brand][:image]
      brand.image = req["public_id"]
    end

    brand.update_attributes brand_params
    redirect_to brand_path(brand)
  end

  def show
    @brand = Brand.find params[:id]
  end

  private

  def brand_params
    params.require(:brand).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/edit.html.erb
<h1>Brands#edit</h1>
<p>Find me in app/views/brands/edit.html.erb</p>

app/views/brands/index.html.erb
<h1>Brands#index</h1>

<% @brands.each do |brand| %>
  <%= link_to brand.name, brand %>
<% end %>

app/views/brands/new.html.erb
<h1>Brands#new</h1>

<%= form_for @brand, :html => {:multipart => true} do |f| %>
  <%= f.label "Brand name:" %>
  <%= f.text_field :name %>

  <!-- SINGLE IMAGE
    <%= f.label "Brand image:" %>
    <%= f.file_field :image %>
  -->

  <%= f.label "Brand images:" %>
  <%= f.file_field :images, :multiple => true %>

  <%= f.submit "Add brand" %>

<% end %>

app/views/brands/show.html.erb
<h1>Brands#show</h1>

<h2><%= @brand.name %></h2>

<!-- SINGLE IMAGE
  <%= cl_image_tag @brand.image %>
-->

<% @brand.images.each do |image| %>
  <%= cl_image_tag image %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SupermarketCloudinary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Home", brands_path %>
    <%= link_to "Add brand", new_brand_path %>
    
    <%= yield %>
  </body>
</html>